openapi: 3.0.0
info:
  title: Flight Ticket Alarm API
  description: API for flight ticket price monitoring
  version: 1.0.0
servers:
  - url: http://localhost:3310
    description: Local development server
